// This file is regenerated by `make typegen` (openapi-typescript).
// Until the backend OpenAPI is generated, hand-typed minimal stubs:

export type User = {
  id: number;
  email: string;
  name: string;
  createdAt: string;
};

export type Post = {
  id: number;
  title: string;
  body: string;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
  published: boolean;
  authorId: number;
};

export type Paginated<T> = {
  data: T[];
  meta: { page: number; pages: number; count: number; items: number };
};

export type AuthResponse = {
  user: User;
  token: string;
};
